### ISSUE TITLE
Youtube Downloader version errors

### ISSUE THREAD

**Issue by SanjivanM** [keotl/mcdisc-resource-builder#12]
So I tried to add in more discs, and I got errors for the videos that were not already downloaded.  Seems like the YouTube video downloader is outdated...  Redownloading the resource pack builder and trying does not help.  I checked the youtube DL repo (https://github.com/ytdl-org/youtube-dl) and it seems that a new version was pushed out a few days ago, which didn't sync with the builder.

Sorry for overly throwing issues here...

I've attached the errors below.
[error.txt](https://github.com/keotl/mcdisc-resource-builder/files/4120152/error.txt)

**Comment by keotl** [comment]
You are absolutely right! I bumped the version to 2020.1.24 which should work correctly now.
