### ISSUE TITLE
No file?

### ISSUE THREAD

**Issue by Phynn2** [keotl/mcdisc-resource-builder#14]
I go to the file and there is nothing to download no exe or anything?

**Comment by Phynn2** [comment]
https://gyazo.com/e9706c9c6f88a1c2186ae68ed979f080

**Comment by keotl** [comment]
Thanks for bringing the issue up. I've fixed the build, and you should now be able to download the tool correctly on the [artifacts page](https://ci.appveyor.com/project/keotl/mcdisc-resource-builder/build/artifacts).

Feel free to re-open if you have other issues.

Cheers!
