### ISSUE TITLE
YouTube videos not downloading

### ISSUE THREAD

**Issue by NachtRaveVL** [keotl/mcdisc-resource-builder#6]
When running, for example on the default sample-disc-config, most videos don't correctly download, and don't correctly build .ogg files associated with them.

Output using default sample-disc-config.json:

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "site-packages\youtube_dl\extractor\youtube.py", line 1191, in _decrypt_signature
  File "site-packages\youtube_dl\extractor\youtube.py", line 1102, in _extract_signature_function
  File "site-packages\youtube_dl\extractor\youtube.py", line 1163, in _parse_sig_js
  File "site-packages\youtube_dl\extractor\common.py", line 796, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Error downloading https://www.youtube.com/watch?v=AEB6ibtdPZc
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "site-packages\youtube_dl\extractor\youtube.py", line 1191, in _decrypt_signature
  File "site-packages\youtube_dl\extractor\youtube.py", line 1102, in _extract_signature_function
  File "site-packages\youtube_dl\extractor\youtube.py", line 1163, in _parse_sig_js
  File "site-packages\youtube_dl\extractor\common.py", line 796, in _search_regex
youtube_dl.utils.RegexNotFoundError: Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by RegexNotFoundError('Unable to extract Initial JS player signature function name; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Error downloading https://www.youtube.com/watch?v=ObmXBy2IyaM

etc,

**Comment by NachtRaveVL** [comment]
On the flip side, I was able to pull up a bash terminal (Ubuntu on Windows) and get pip and such working by manually invoking the main.py script, but only after manually forced updating of youtube-dl. Looks like it may just be an issue of needing the more recent downloader into the built application.

**Comment by keotl** [comment]
I have updated youtube-dl to version 2019.4.1
